include("testejercicio2.jl")
title("Ejercicio 9.6.4 - 2, Y vs Yr")
plot(t22, [x[2] for x in vecs22], label="y")
plot(t22, [x[5] for x in vecs22], label="yr")
xlabel("t")
ylabel("y, yr")
legend()
show()